### ISSUE TITLE
"error: failed to run custom build command for vtrace v0.1.0" compiling on Windows

### ISSUE THREAD

**Issue by DynamicGoose** [RArbore/vtrace#1]
### The error I am getting after running `cargo run` with RUST_BACKTRACE=full :
error: failed to run custom build command for `vtrace v0.1.0 (D:\github\vtrace)`

Caused by:
  process didn't exit successfully: `D:\github\vtrace\target\debug\build\vtrace-0204edc84e53b783\build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: NotFound, message: "program not found" }', build.rs:64:14
  stack backtrace:
     0:     0x7ff68eb97e62 - std::backtrace_rs::backtrace::dbghelp::trace
                                 at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
     1:     0x7ff68eb97e62 - std::backtrace_rs::backtrace::trace_unsynchronized
                                 at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
     2:     0x7ff68eb97e62 - std::sys_common::backtrace::_print_fmt
                                 at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\sys_common\backtrace.rs:65
     3:     0x7ff68eb97e62 - std::sys_common::backtrace::_print::impl$0::fmt
                                 at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\sys_common\backtrace.rs:44
     4:     0x7ff68ebb0bcb - core::fmt::write
                                 at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\core\src\fmt\mod.rs:1209
     5:     0x7ff68eb9458a - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                                 at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\io\mod.rs:1682
     6:     0x7ff68eb97bab - std::sys_common::backtrace::_print
                                 at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\sys_common\backtrace.rs:47
     7:     0x7ff68eb97bab - std::sys_common::backtrace::print
                                 at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\sys_common\backtrace.rs:34
     8:     0x7ff68eb9a819 - std::panicking::default_hook::closure$1
                                 at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\panicking.rs:267
     9:     0x7ff68eb9a49a - std::panicking::default_hook
                                 at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\panicking.rs:286
    10:     0x7ff68eb9b0a1 - std::panicking::rust_panic_with_hook
                                 at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\panicking.rs:688
    11:     0x7ff68eb9ae2d - std::panicking::begin_panic_handler::closure$0
                                 at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\panicking.rs:579
    12:     0x7ff68eb98b6f - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                                 at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\sys_common\backtrace.rs:137
    13:     0x7ff68eb9aaf0 - std::panicking::begin_panic_handler
                                 at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\panicking.rs:575
    14:     0x7ff68ebb6c25 - core::panicking::panic_fmt
                                 at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\core\src\panicking.rs:65
    15:     0x7ff68ebb6e53 - core::result::unwrap_failed
                                 at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\core\src\result.rs:1791
    16:     0x7ff68eb8924a - enum2$<core::result::Result<std::process::ExitStatus,std::io::error::Error> >::unwrap<std::process::ExitStatus,std::io::error::Error>
                                 at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943\library\core\src\result.rs:1113
    17:     0x7ff68eb839c7 - build_script_build::main
                                 at d:\github\vtrace\build.rs:52
    18:     0x7ff68eb86dcb - core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
                                 at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943\library\core\src\ops\function.rs:251
    19:     0x7ff68eb8814e - std::sys_common::backtrace::__rust_begin_short_backtrace<void (*)(),tuple$<> >
                                 at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943\library\std\src\sys_common\backtrace.rs:121
    20:     0x7ff68eb8814e - std::sys_common::backtrace::__rust_begin_short_backtrace<void (*)(),tuple$<> >
                                 at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943\library\std\src\sys_common\backtrace.rs:121
    21:     0x7ff68eb85791 - std::rt::lang_start::closure$0<tuple$<> >
                                 at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943\library\std\src\rt.rs:166
    22:     0x7ff68eb90f9e - core::ops::function::impls::impl$2::call_once
                                 at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\core\src\ops\function.rs:286
    23:     0x7ff68eb90f9e - std::panicking::try::do_call
                                 at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\panicking.rs:483
    24:     0x7ff68eb90f9e - std::panicking::try
                                 at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\panicking.rs:447
    25:     0x7ff68eb90f9e - std::panic::catch_unwind
                                 at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\panic.rs:137
    26:     0x7ff68eb90f9e - std::rt::lang_start_internal::closure$2
                                 at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\rt.rs:148
    27:     0x7ff68eb90f9e - std::panicking::try::do_call
                                 at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\panicking.rs:483
    28:     0x7ff68eb90f9e - std::panicking::try
                                 at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\panicking.rs:447
    29:     0x7ff68eb90f9e - std::panic::catch_unwind
                                 at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\panic.rs:137
    30:     0x7ff68eb90f9e - std::rt::lang_start_internal
                                 at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\rt.rs:148
    31:     0x7ff68eb8576a - std::rt::lang_start<tuple$<> >
                                 at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943\library\std\src\rt.rs:165
    32:     0x7ff68eb84179 - main
    33:     0x7ff68ebb5580 - invoke_main
                                 at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
    34:     0x7ff68ebb5580 - __scrt_common_main_seh
                                 at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    35:     0x7ffaa33755a0 - BaseThreadInitThunk
    36:     0x7ffaa3cc485b - RtlUserThreadStart

**Comment by RArbore** [comment]
I wrote the build script with Linux usage in mind, so it invokes the system C compiler as "cc" directly. I don't use Windows, so I'm not sure what the solution would be to build vtrace on windows.

There are likely a decent amount of other Linux specific things throughout vtrace.

**Comment by DynamicGoose** [comment]
I'll try running it on linux then. 
Maybe you could add that to the readme, so other people know?
Anyway, thanks for the tip!

**Comment by DynamicGoose** [comment]
### After finally getting glfw working it still doesn't compile even under Linux. 
**New error:**

error: failed to run custom build command for `vtrace v0.1.0 (/home/user/vtrace)`

Caused by:
  process didn't exit successfully: `/home/user/vtrace/target/debug/build/vtrace-9d973183114f5b98/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=lib/entry.c
  cargo:rerun-if-changed=lib/descriptor.c
  cargo:rerun-if-changed=lib/device.c
  cargo:rerun-if-changed=lib/swapchain.c
  cargo:rerun-if-changed=lib/pipeline.c
  cargo:rerun-if-changed=lib/raytrace.c
  cargo:rerun-if-changed=lib/command.c
  cargo:rerun-if-changed=lib/memory.c
  cargo:rerun-if-changed=lib/sync.c
  cargo:rerun-if-changed=lib/util/dynarray.c

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', build.rs:84:10

_I will investigate this further tomorrow, but I need to get some sleep first._

**Comment by RArbore** [comment]
Reopen if you're still running into issues with the build script. Also, the hardware ray tracing work in this repo is very unfinished - if you want to run anything, you should run off the last commit in the raster-fix branch, which will run the raster-based pipeline.

**Comment by DynamicGoose** [comment]
No issues compiling on Linux so far!
Still get the same error in Windows!
