### ISSUE TITLE
thread 'main' panicked at 'ERROR: Vulkan initialization failed', src/render.rs:187:13 (RUST_BACKTRACE=1)

### ISSUE THREAD

**Issue by DynamicGoose** [RArbore/vtrace#3]
### The Error I'm getting:

thread 'main' panicked at 'ERROR: Vulkan initialization failed', src/render.rs:187:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:65:14
   2: vtrace::render::Renderer::new
             at ./src/render.rs:187:13
   3: vtrace::main
             at ./src/main.rs:27:40
   4: core::ops::function::FnOnce::call_once
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/ops/function.rs:251:5

#### This error could be caused by me being dumb and having missing deps. I have the vukan-intel and vulkan-devel package installed on an arch system.

**Comment by RArbore** [comment]
This is on the raster-fix branch right? I stopped development on this project some time ago, so the main branch is in an unfinished state w/ some acceleration structure building commands.

**Comment by DynamicGoose** [comment]
I was still on the main branch. I'll try the raster-fix branch!

**Comment by DynamicGoose** [comment]
It works with the rater-fix branch! Thanks.
(I didn't read the last response to my other issue sry)
